# Generated by Django 3.0.5 on 2021-04-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_number', models.IntegerField()),
                ('prescription_issue_date', models.DateField()),
                ('times_per_day', models.IntegerField()),
                ('medicine', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('revisit', models.IntegerField()),
                ('tests', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Note Date')),
                ('content', models.CharField(max_length=250)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Prescription')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dosing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Administration Date')),
                ('time', models.TimeField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Prescription')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
