# Generated by Django 3.0.5 on 2021-04-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='test',
            new_name='condition',
        ),
    ]
